name: Fitpause CICD Pipeline
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Install dependencies
        run: |
          if [ -f package.json ]; then
            npm install
          else
            echo "No package.json found, skipping dependencies"
          fi
      
      - name: Run ESLint
        run: |
          if [ -f package.json ]; then
            npm run lint || echo "Lint not configured, skipping..."
          else
            echo "No package.json found, skipping lint"
          fi
      
      - name: Run Tests
        run: |
          if [ -f package.json ]; then
            npm run test || echo "Tests not configured, skipping..."
          else
            echo "No package.json found, skipping tests"
          fi
  
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Install dependencies
        run: |
          if [ -f package.json ]; then
            npm install
          else
            echo "No package.json found, skipping dependencies"
          fi
      
      - name: Build project
        run: |
          if [ -f package.json ]; then
            npm run build || echo "Build not configured, skipping..."
          else
            echo "No package.json found, skipping build"
          fi
