name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * 0' # Weekly on Sunday at 2 AM

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'
    
    - name: Upload Trivy scan results to GitHub Security
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-results.sarif'
    
    - name: GDPR Compliance Check
      run: |
        # Check for hardcoded personal data
        grep -r "email.*@" src/ && exit 1 || echo "No hardcoded emails found"
        grep -r "password" src/ && exit 1 || echo "No hardcoded passwords found"
        
        # Verify privacy policy exists
        test -f "src/pages/privacy.html" || exit 1
        
        # Check cookie consent implementation
        grep -q "cookie.*consent" src/index.html || exit 1
